# Generated by Django 5.2.13 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_projeto', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_prazo', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'projetos',
                'managed': False,
            },
        ),
    ]
