# Generated by Django 5.2.13 on 2026-05-05 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'managed': False},
        ),
    ]
