# Generated by Django 5.2.13 on 2026-05-05 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='usuarios',
        ),
    ]
